# Generated by Django 4.1.5 on 2023-06-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password1',
        ),
    ]
